name: build-debug

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: sudo apt-get install libncurses5-dev libncursesw5-dev
    - name: make
      run: make debug
